# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    node: /usr/bin/nodejs
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
        uglifyjs2:
            # the path to the uglifyjs executable
            bin: %kernel.root_dir%/../node_modules/.bin/uglifyjs
        uglifycss:
            bin: %kernel.root_dir%/../node_modules/.bin/uglifycss
    assets:
        app_css:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/css/bootstrap.min.css
            filters:
                - cssrewrite
                - uglifycss
            output: "css/app.css"
        jquery:
            inputs:
                - %kernel.root_dir%/../vendor/frameworks/jquery/jquery.js
            filters:
                - uglifyjs2
            output: "js/jquery.js"
        app_js:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/js/bootstrap.js
            filters:
                - uglifyjs2
            output: "js/app.js"
